[package]
name = "phoneme"
edition = "2018"
version = "0.0.1"
authors = [
  "Brandon Thomas <bt@brand.io>",
  "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[dependencies]
log = "0.4.8"
ndarray = "0.13.1"
ndarray-npy = "0.5.0"

[dev-dependencies]
anyhow = "1.0.31"
