[package]
name = "phoneme"
edition = "2018"
version = "0.0.1"
authors = [
  "Brandon Thomas <bt@brand.io>",
  "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[dependencies]
anyhow = "1.0.31"
log = "0.4.8"
numpy = "0.11"

